FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

COPY . .
RUN rm -rf node_modules
RUN if [ -f package-lock.json ]; then npm ci; else npm install; fi
RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start:prod"]
