FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

COPY . .
RUN rm -rf node_modules
RUN npm install

EXPOSE 5173

CMD ["sh", "-c", "if [ -f vite.config.js ] || [ -f vite.config.ts ]; then npm run dev -- --host 0.0.0.0; else npm run start -- --host 0.0.0.0; fi"]
